### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by BryanDonovan**
Various cleanup, adding jshint, adding nodeunit to package.json.

### CODE REVIEW

**Comment by kontrafiktion** [comment]
Hi Bryan!

Thanks for contributing

Victor

**Comment by BryanDonovan** [comment]
Thanks!

**Comment by BryanDonovan** [comment]
Hi Victor,

Can you please run 'npm publish' to publish the latest version to the npm repository?

Thanks!
Bryan

**Comment by kontrafiktion** [comment]
done (accidentally twice, so it is now at 0.0.5)

**Comment by BryanDonovan** [comment]
thanks!

**Pull request merged**
